export const actionTypes = {
  //Album
  SET_ALBUMID: "SET_ALBUMID",
  //

  // CONTROLPLAYER
  SET_SONGID: "SET_SONGID",
  SET_PLAY: "SET_PLAY",
  SET_SHUFFLE: "SET_SHUFFLE",
  SET_BACKMUSIC: "SET_BACKMUSIC",
  SET_NEXTMUSIC: "SET_NEXTMUSIC",
  SET_PLAYLIST: "SET_PLAYLIST",
  SET_INDEXSONGPLAYLIST: "SET_INDEXSONGPLAYLIST",
};
